### ISSUE TITLE
MW 1.41 - Call to undefined method WikiPage::factory()

### ISSUE THREAD

**Issue by thomas-topway-it** [gesinn-it-pub/IDProvider#19]
as for the title
`
Call to undefined method WikiPage::factory() ...extensions/IDProvider/src/IdProvider.php(50)
`

it could be updated as follows:

```

	private static function isUniqueId() {
		return function ( $id ) {
			$title = Title::newFromText( $id );
			$page = WikiPage::factory( $title );
			
			// MW 1.36+
			$page = method_exists( MediaWikiServices::class, 'getWikiPageFactory' )
				? MediaWikiServices::getInstance()->getWikiPageFactory()->newFromTitle( $title )
				:  WikiPage::factory( $title );

			return !$page->exists();
		};
	}
```

use-case: https://wikisphere.org/wiki/Demo_VisualData/CRUD

**Comment by gesinn-it-gea** [comment]
@gesinn-it-ilm can you please confirm (ideally with a test)

**Comment by gesinn-it-ilm** [comment]
@gesinn-it-gea - I think that `WikiPage::factory()` has been removed and not exists in MW 1.43. 
We should use PageStorage probably in this case. 
Something like this:
`$pageStore = MediaWikiServices::getInstance()->getPageStore();
$page = $pageStore->getPageForTitle( $title );`
I will check everything.

**Comment by thomas-topway-it** [comment]
I confirm that `newFromTitle`'s `WikiPageFactory` both exist on MW 1.42.1 and are not deprecated, `WikiPage::factory` is for MW 1.35 if you want to support it

**Comment by thomas-topway-it** [comment]
so it could be something like that 

```
	private static function isUniqueId() {
		return function ( $id ) {
			if ( class_exists( 'MediaWiki\Page\PageStore' ) ) {		
				$pageStore = MediaWikiServices::getInstance()->getPageStore();
				$page = $pageStore->getPageById( $id );
			} else {			
				$title = Title::newFromText( $id );
				$page = MediaWikiServices::getInstance()
					->getWikiPageFactory()->newFromTitle( $title );
			}
			return ( !$page || !$page->exists() );
		};
	}
```

(to be tested)

**Comment by gesinn-it-ilm** [comment]
Working on it already.

**Comment by thomas-topway-it** [comment]
sorry, `Title::newFromID( $id )`, not  `Title::newFromText( $id )`

**Comment by gesinn-it-ilm** [comment]
@thomas-topway-it - I have run the tests for the code you have refactored before, this one: 

`private static function isUniqueId() {
		return function ( $id ) {
			$title = Title::newFromText( $id );
			$page = WikiPage::factory( $title );
			
			// MW 1.36+
			$page = method_exists( MediaWikiServices::class, 'getWikiPageFactory' )
				? MediaWikiServices::getInstance()->getWikiPageFactory()->newFromTitle( $title )
				:  WikiPage::factory( $title );

			return !$page->exists();
		};
	}`

- all seems to work fine, for **MW 1.40, MW 1.41 and MW 1.43** as well.

**Comment by gesinn-it-ilm** [comment]
@thomas-topway-it - All clear. Then I will update that part and test again.

**Comment by gesinn-it-ilm** [comment]
This is checked, the tests are added to cover `isUniqueId()` from `IdProviderFactory.php`.
The code coverage is increased now. 
`Title::newFromID( $id )` - added to the `isUniqueId()`, as well as some additional checks.
